name: TranscEndence
version: ${project.version}
author: sfiguz7
description: A Slimefun4 Addon for more End content
website: https://github.com/Sfiguz7/TranscEndence

main: me.sfiguz7.transcendence.TranscEndence
depend: [Slimefun]
softdepend:
  - GuizhanLibPlugin

api-version: 1.14

commands:
  transcendence:
    description: basic TranscEndence command
    aliases: te
    usage: You either forgot to install CS-CoreLib or you installed an unsupported version.

permissions:
  te.command.reapply:
    description: Allows you to reapply Daxi effects to players
    default: op
  te.command.toggle:
    description: Allows you to toggle Daxi effects refreshing for players
    default: op
